<a href="https://colab.research.google.com/github/Auzzer/QuickPytorchTutor/blob/main/QuickPytorchTutor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor (张量)的创建与基本操作
张量是GPU运算中常见的数据类型，类似于Numpy中的矩阵，但是由于深度学习中常常需要使用GPU进行并行运算，提升计算速度，因此使用Tensor

## 创建

In [2]:
import torch

In [11]:
# 创建一个张量通常需要初始化，我们一般使用：
x1 = torch.empty(5, 3) #一个5x3的张量
print(x1)

# 随机初始化张量
x2 = torch.rand(5, 3)
print(x2)

# 在初始化张量时，有时需要指定数据类型：
x3 = torch.zeros(5, 3, dtype=torch.long) #创建一个数据类型为long的"0"填充矩阵
print(x3)

# 如果已知一个矩阵，将其转化为张量加速计算
x4 = torch.tensor([[1,2,3],[6,7,8]]) 
print(x4)

tensor([[4.3773e+24, 3.0725e-41, 2.8026e-45],
        [0.0000e+00, 4.2039e-45, 0.0000e+00],
        [8.4078e-45, 0.0000e+00, 9.8091e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.6326, 0.1925, 0.2692],
        [0.3430, 0.6707, 0.9599],
        [0.9630, 0.5290, 0.7859],
        [0.8153, 0.7201, 0.8248],
        [0.7111, 0.5788, 0.2456]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1, 2, 3],
        [6, 7, 8]])


In [12]:
# 获取size
print(x4.size()) # 结果表示为两行三列

torch.Size([2, 3])


## Basic Product


### 加法

In [27]:
# 对于一个最简单的加法
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print (x+y)
# 或者
print (torch.add(x, y))

# 对于torch.add(),有一个option可以将结果保存下来,但是首先需要将结果初始化
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print("result: \n",result)

#特别值得注意的是，torch.add()函数只能对两个张量进行运算，当数量大于二的时候：
y1 = torch.zeros(5, 3)
y2 = torch.empty(5, 3)
for i in range(0, 5):
  xi = torch.rand(5, 3)
  y1.add(xi)
  y2.add(xi)

print("y1\n",y1)
print("y2\n",y2)
# 结果显示在做加法的时候，由于empty张量会随机给一个值，所以应该使用"zeros张量"

tensor([[1.8637, 0.8841, 0.3732],
        [0.6292, 1.1238, 1.2939],
        [1.1554, 0.9996, 0.8031],
        [1.7773, 1.0039, 1.4080],
        [0.8788, 0.7864, 0.7202]])
tensor([[1.8637, 0.8841, 0.3732],
        [0.6292, 1.1238, 1.2939],
        [1.1554, 0.9996, 0.8031],
        [1.7773, 1.0039, 1.4080],
        [0.8788, 0.7864, 0.7202]])
tensor([[1.8637, 0.8841, 0.3732],
        [0.6292, 1.1238, 1.2939],
        [1.1554, 0.9996, 0.8031],
        [1.7773, 1.0039, 1.4080],
        [0.8788, 0.7864, 0.7202]])
y1
 tensor([[2.5804, 1.9542, 2.7683],
        [2.3748, 2.7451, 1.6035],
        [2.7108, 2.4057, 2.3366],
        [3.9157, 2.9352, 2.8133],
        [3.1810, 2.2222, 1.8287]])
y2
 tensor([[4.3765e+24, 1.9542e+00, 5.1006e+00],
        [5.0222e+00, 4.9549e+00, 3.1798e+00],
        [4.7230e+00, 4.3089e+00, 3.9306e+00],
        [7.3395e+00, 4.5747e+00, 4.9997e+00],
        [5.2263e+00, 4.3514e+00, 4.5425e+00]])


### 乘法
在矩阵中，乘法有点乘和叉乘两种，张量也有相对应的不同计算方法

In [29]:
# 点乘
x1 = torch.rand(5, 3)
x2 = torch.rand(5, 3)
y = torch.mul(x1, x2)# 类似与上文的add，在多个张量可以使用x1.mul(x2)
print("x1:\n", x1, "\n x2:\n", x2, "\n y:\n",y)

# 叉乘
x1 = torch.rand(2, 3)
x2 = torch.rand(3, 4)
y = torch.mm(x1, x2)# 类似与上文的add，在多个张量可以使用x1.mm(x2)
print("x1:\n", x1, "\nx2:\n", x2, "\ny:\n",y)

x1:
 tensor([[3.4130e-01, 7.1896e-01, 4.0122e-01],
        [4.4395e-01, 4.7499e-01, 9.2966e-01],
        [6.5652e-02, 4.7017e-01, 7.5633e-01],
        [7.3802e-01, 1.7166e-01, 4.6248e-01],
        [4.1113e-01, 2.7661e-01, 1.5497e-04]]) 
 x2:
 tensor([[0.0041, 0.5140, 0.0541],
        [0.7816, 0.9990, 0.2608],
        [0.2597, 0.0236, 0.2706],
        [0.7921, 0.0189, 0.5529],
        [0.7623, 0.7521, 0.1769]]) 
 y:
 tensor([[1.4121e-03, 3.6954e-01, 2.1710e-02],
        [3.4698e-01, 4.7453e-01, 2.4249e-01],
        [1.7049e-02, 1.1105e-02, 2.0468e-01],
        [5.8458e-01, 3.2442e-03, 2.5570e-01],
        [3.1339e-01, 2.0804e-01, 2.7414e-05]])
x1:
 tensor([[0.0552, 0.9164, 0.2524],
        [0.0760, 0.2871, 0.9371]]) 
x2:
 tensor([[0.5551, 0.5035, 0.2915, 0.4963],
        [0.2515, 0.5803, 0.8617, 0.6428],
        [0.6847, 0.6481, 0.6611, 0.2976]]) 
y:
 tensor([[0.4339, 0.7231, 0.9726, 0.6915],
        [0.7560, 0.8122, 0.8891, 0.5011]])


### Numpy中的对应与转化

#### 索引
torch支持使用类似于Numpy中的索引对张量进行操作


In [6]:
x = torch.tensor([[1,2,3],[3,4,5]])
print(x[:,0])
print(x[1,:])

tensor([1, 3])
tensor([3, 4, 5])


#### 在numpy中reshape对应

In [8]:
x = torch.randn(5, 3)
y = x.view(3, 5)
z = x.view(-1, 5) # 当选项中有一个-1时候，代表从另外一个维度考虑转化方式
print(x)
print(y)
print(z)

tensor([[ 0.2350, -0.7981, -1.3963],
        [-0.5878,  0.7670,  1.4030],
        [ 0.1570, -1.0562,  1.8708],
        [-0.3263,  1.8232, -0.2369],
        [ 0.1883,  1.0110, -0.3872]])
tensor([[ 0.2350, -0.7981, -1.3963, -0.5878,  0.7670],
        [ 1.4030,  0.1570, -1.0562,  1.8708, -0.3263],
        [ 1.8232, -0.2369,  0.1883,  1.0110, -0.3872]])
tensor([[ 0.2350, -0.7981, -1.3963, -0.5878,  0.7670],
        [ 1.4030,  0.1570, -1.0562,  1.8708, -0.3263],
        [ 1.8232, -0.2369,  0.1883,  1.0110, -0.3872]])


### 覆盖操作
任何以"_"结尾的函数（操作）都会替换原来的变量

In [19]:
x1 = torch.rand(5, 3)
print("覆盖以前的x1:\n", x1)
x2 = torch.rand(5, 3)
y = x1.add_(x2)
print("覆盖以后的x1:\n", x1)
print(y)

覆盖以前的x1:
 tensor([[0.4530, 0.5302, 0.8162],
        [0.1162, 0.3626, 0.5144],
        [0.5313, 0.8675, 0.4438],
        [0.4011, 0.6296, 0.2395],
        [0.4407, 0.7304, 0.2312]])
覆盖以后的x1:
 tensor([[0.5994, 0.6711, 0.9561],
        [0.5438, 0.8049, 0.7759],
        [0.7994, 1.4201, 1.2093],
        [1.3453, 0.9124, 0.2621],
        [1.1335, 0.8059, 0.5170]])
tensor([[0.5994, 0.6711, 0.9561],
        [0.5438, 0.8049, 0.7759],
        [0.7994, 1.4201, 1.2093],
        [1.3453, 0.9124, 0.2621],
        [1.1335, 0.8059, 0.5170]])


可以看到x1的值发生了变化,但是和y的值是一样的<br>
更多对于tensor的operation可以参考官方文档：https://pytorch.org/docs/stable/torch.html


## Cuda加速
在这里我们先提出一个概念：
为了计算加速，有一些数据可以被放入cuda中加速计算，在这里我们先将tensor放入cuda中，第一步需要先判定是否有cuda(GPU)可以使用

In [15]:
x = torch.rand(5, 3)
if torch.cuda.is_available():
  device = torch.device("cuda")
  # 下面分别从cuda中直接生成tensor以及将tensor生成后放进cuda中
  x = x.to(device)
  y = torch.ones_like(x, device=device)
  z = x + y
print(z)
print(z.to("cpu", torch.double))


tensor([[ 0.2350, -0.7981, -1.3963, -0.5878,  0.7670],
        [ 1.4030,  0.1570, -1.0562,  1.8708, -0.3263],
        [ 1.8232, -0.2369,  0.1883,  1.0110, -0.3872]])
tensor([[ 0.2350, -0.7981, -1.3963, -0.5878,  0.7670],
        [ 1.4030,  0.1570, -1.0562,  1.8708, -0.3263],
        [ 1.8232, -0.2369,  0.1883,  1.0110, -0.3872]], dtype=torch.float64)


# 神经网络训练

## 数据加载

## 定义网络

## 训练策略

### 求导机制

### 学习率设置

### Batch设置

## 可视化

### 本地保存

### 利用TensorBoardX

## Pre-Train & Fine-Tune